use std::path::Path;

/// Parse `generate_handler![...]` command names from `src/lib.rs` for ACL codegen.
fn parse_invoke_commands(manifest_dir: &Path) -> Vec<String> {
    let lib_rs =
        std::fs::read_to_string(manifest_dir.join("src/lib.rs")).expect("read src/lib.rs");
    let marker = ".invoke_handler(tauri::generate_handler![";
    let start = lib_rs
        .find(marker)
        .expect("invoke_handler block in lib.rs")
        + marker.len();
    let rest = &lib_rs[start..];
    let end = rest
        .find("\n        ])")
        .expect("invoke_handler closing bracket");
    let block = &rest[..end];

    let mut commands = Vec::new();
    let mut in_cfg = false;
    for line in block.lines() {
        let line = line.trim();
        if line.starts_with("#[cfg") {
            in_cfg = true;
            if line.ends_with(")]") {
                in_cfg = false;
            }
            continue;
        }
        if in_cfg {
            if line.ends_with(")]") {
                in_cfg = false;
            }
            continue;
        }
        if let Some(name) = parse_command_ident(line) {
            commands.push(name);
        }
    }
    commands
}

fn parse_command_ident(line: &str) -> Option<String> {
    let line = line.trim().trim_end_matches(',');
    if line.is_empty() || line.starts_with("//") {
        return None;
    }
    if !line
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == ':')
    {
        return None;
    }
    let name = line.rsplit("::").next()?.to_string();
    if name
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '_')
    {
        Some(name)
    } else {
        None
    }
}

/// Grant every app command to bundled/localhost origins (Tauri 2.11.1+ ACL).
/// The permission set id must NOT be `default` — that collides with the main
/// capability identifier and recurses until stack overflow at runtime.
fn write_app_command_permissions(manifest_dir: &Path, commands: &[String]) {
  const PERMISSION_SET: &str = "app-command-acl";

  let permissions_dir = manifest_dir.join("permissions");
  std::fs::create_dir_all(&permissions_dir).expect("create permissions dir");

  let mut body = String::from(
    r#"# Autogenerated by build.rs — do not edit.
# Tauri 2.11.1+ treats http://localhost as a remote origin; the main capability
# references this set so bundled frontend IPC keeps working.

"#,
  );
  body.push_str("[[set]]\n");
  body.push_str(&format!("identifier = \"{PERMISSION_SET}\"\n"));
  body.push_str(
    r#"description = """
Default permission set for all application #[tauri::command] handlers.
Required for localhost-served release builds (tauri-plugin-localhost).
"""
permissions = [
"#,
  );
  for command in commands {
    let slug = command.replace('_', "-");
    body.push_str(&format!("  \"allow-{slug}\",\n"));
  }
  body.push_str("]\n");

  let path = permissions_dir.join("app-command-acl.toml");
  if std::fs::read_to_string(&path).ok().as_deref() != Some(body.as_str()) {
    std::fs::write(&path, body).expect("write permissions/app-command-acl.toml");
  }
  println!("cargo:rerun-if-changed={}", path.display());
}

fn leaked_command_slice(commands: &[String]) -> &'static [&'static str] {
    let leaked: Vec<&'static str> = commands
        .iter()
        .map(|command| {
            let boxed: Box<str> = command.clone().into_boxed_str();
            let leaked: &'static str = Box::leak(boxed);
            leaked
        })
        .collect();
    Box::leak(leaked.into_boxed_slice())
}

/// Extract all LC_RPATH paths from a Mach-O binary via `otool -l`.
/// Returns an empty vec if otool is unavailable or the binary isn't a Mach-O.
fn read_rpaths(binary: &std::path::Path) -> Vec<String> {
    let output = match std::process::Command::new("otool")
        .args(["-l", &binary.to_string_lossy()])
        .output()
    {
        Ok(o) => o,
        Err(_) => return Vec::new(),
    };
    let stdout = String::from_utf8_lossy(&output.stdout);

    // otool prints LC_RPATH entries as two consecutive lines, e.g.:
    //       cmd LC_RPATH
    //   cmdsize 48
    //      path @executable_path/../Resources/bin (offset 12)
    // We walk the lines, and whenever we see `cmd LC_RPATH`, the `path` field
    // follows within the next few lines.
    let lines: Vec<&str> = stdout.lines().collect();
    let mut rpaths = Vec::new();
    let mut i = 0;
    while i < lines.len() {
        let trimmed = lines[i].trim();
        if trimmed.ends_with("LC_RPATH") {
            // Look ahead for the `path ...` line.
            for &peek in lines.iter().take((i + 4).min(lines.len())).skip(i + 1) {
                let p = peek.trim();
                if let Some(rest) = p.strip_prefix("path ") {
                    if let Some(path) = rest.split_whitespace().next() {
                        rpaths.push(path.to_string());
                    }
                    break;
                }
            }
        }
        i += 1;
    }
    rpaths
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=windows/app.manifest");

    #[cfg(target_os = "windows")]
    {
        let manifest_dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let manifest = manifest_dir.join("windows/app.manifest");
        if manifest.is_file() {
            let mut res = tauri_winres::WindowsResource::new();
            res.set_manifest_file(&manifest.to_string_lossy());
            if let Err(err) = res.compile() {
                panic!("failed to compile Windows application manifest: {err}");
            }
        }
    }

    // Expose the full Rust target triple to the library crate as a compile-time
    // env var. Used by engine.rs / model_manager.rs to build sidecar binary paths
    // that match Tauri's externalBin naming convention (<name>-<target-triple>).
    // `std::env::var("TARGET")` is only available here in build.rs, not in lib code.
    let target_triple = std::env::var("TARGET").unwrap_or_default();
    println!("cargo:rustc-env=TAURI_TARGET_TRIPLE={}", target_triple);

    // Ensure 0-byte sidecar placeholders exist for the current target.
    // Tauri's bundler requires every externalBin entry to be present at build time.
    // If the real binary can't be downloaded (e.g. CI without network), a 0-byte
    // placeholder keeps the build from failing. At runtime, engine.rs detects the
    // empty/placeholder sidecar and returns a clear "sidecar not available" error
    // instead of trying to execute it; model_manager.rs reports such models as not
    // installed.
    let bin_dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("bin");
    if bin_dir.is_dir() {
        let target = std::env::var("TARGET").unwrap_or_default();
        if !target.is_empty() {
            // Seed 0-byte placeholders for every externalBin entry that isn't already
            // present. Tauri's bundler checks all externalBin paths at build time and
            // fails with "resource path `bin/<name>-<triple>` doesn't exist" if any is
            // missing. The real binaries are provisioned at build/release time by
            // scripts/download-sidecars.js (or, historically, were committed to git),
            // but `cargo test`/`cargo check` workflows like CI Regression Gate don't
            // run that script. A 0-byte placeholder satisfies the bundler; at runtime,
            // engine.rs::check_sidecar_usable detects the empty sidecar and returns a
            // clear "sidecar not available" error instead of trying to execute it.
            // Only externalBin entries without a committed launcher need this —
            // pocket-tts-* launchers are tracked in git, so they always resolve.
            for base in ["whisper", "sherpa-onnx", "sherpa-online"] {
                let sidecar_name = if target.contains("windows") {
                    format!("{}-{}.exe", base, target)
                } else {
                    format!("{}-{}", base, target)
                };
                let sidecar_path = bin_dir.join(&sidecar_name);
                if !sidecar_path.exists() {
                    std::fs::write(&sidecar_path, []).ok();
                }
            }

            // Seed a placeholder shared library so the platform resource globs
            // in tauri.linux.conf.json (`bin/*.so*`) and the Windows config
            // (`bin/*.dll`) never match zero files — Tauri hard-fails the build
            // in that case. The real libraries are dropped into bin/ by
            // download-sidecars.js; cargo test/check workflows don't run that
            // script, so without a placeholder the Linux build dies with
            // "glob pattern bin/*.so* path not found". A 0-byte placeholder
            // satisfies the glob and is gitignored (see *.placeholder.so /
            // *.placeholder.dll). It never enters the real sidecar path.
            if target.contains("linux") {
                let placeholder = bin_dir.join("libplaceholder.so");
                if !placeholder.exists() {
                    std::fs::write(&placeholder, []).ok();
                }
            }

            // macOS bundles declare `bin/*.dylib` as a resource. Keep local
            // cargo/tauri-dev builds working when the optional native
            // transcription libraries have not been downloaded yet; the real
            // dylibs provisioned by download-sidecars.js replace this marker.
            if target.contains("apple-darwin") {
                let placeholder = bin_dir.join("libplaceholder.dylib");
                if !placeholder.exists() {
                    std::fs::write(&placeholder, []).ok();
                }
            }
        }
    }

    // On macOS, fix the whisper/sherpa sidecar binaries' dylib references.
    //
    // Why this matters: these sidecars are dynamically linked
    // (`@rpath/libwhisper.1.dylib`, `@rpath/libggml*.dylib`, `@rpath/libonnxruntime*.dylib`).
    // dyld resolves `@rpath/...` against the binary's LC_RPATH entries. Without the
    // right rpath(s), launching the sidecar dies at startup with
    // "dyld: Library not loaded: @rpath/libwhisper.1.dylib" — which silently breaks
    // *every* transcription (Distil / base / small all share the whisper sidecar)
    // before any model-specific code runs.
    //
    // Two distinct layouts must both work:
    //   • Production (bundled .app): sidecar at Contents/MacOS/<name>, dylibs at
    //     Contents/Resources/bin/*.dylib  → needs rpath "@executable_path/../Resources/bin".
    //   • Dev (tauri dev / cargo build): sidecar runs straight out of src-tauri/bin/
    //     with the dylibs beside it  → needs rpath "@executable_path".
    // We add BOTH rpaths so dylib resolution succeeds in either layout, and we
    // strip stale /Volumes/external/... LC_RPATH entries left over from the build host
    // (those are tried first and mask the correct ones).
    //
    // install_name_tool mutates the Mach-O load commands, which invalidates the
    // embedded ad-hoc signature. On Apple Silicon, an unsigned/invalid binary is
    // SIGKILL'd by the kernel, so we re-sign ad-hoc with codesign afterward.
    if cfg!(target_os = "macos") {
        // Apple FM Swift bridge references libswift_* via @rpath; the main binary must
        // inherit an LC_RPATH or dyld dies before main() with "Check with the developer…".
        println!("cargo:rustc-link-arg=-Wl,-rpath,/usr/lib/swift");

        let bin_dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("bin");

        // Both production and dev rpaths must be present on every macOS sidecar.
        const RPATHS: [&str; 2] = [
            "@executable_path/../Resources/bin", // production .app layout
            "@executable_path",                  // dev layout (dylibs beside the binary)
        ];

        let sidecar_bins: Vec<std::path::PathBuf> = std::fs::read_dir(&bin_dir)
            .into_iter()
            .flatten()
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| {
                let name = p
                    .file_name()
                    .and_then(|n| n.to_str())
                    .unwrap_or("")
                    .to_string();
                let is_apple = name.contains("apple");
                (name.starts_with("whisper-") || name.starts_with("sherpa-")) && is_apple
            })
            .collect();

        for binary_path in &sidecar_bins {
            // Skip 0-byte placeholder sidecars (e.g. an unbuilt sidecar without a
            // prebuilt asset); install_name_tool/codesign would fail on them, and
            // they're handled by the runtime checks in engine.rs / model_manager.rs.
            match std::fs::metadata(binary_path) {
                Ok(md) if md.len() == 0 => continue,
                Ok(_) => {}
                Err(_) => continue,
            }

            // IDEMPOTENCE: this build script runs on every cargo invocation, and in
            // `tauri dev` the file-watcher treats any change under bin/ as a reason to
            // rebuild. If we unconditionally re-sign/re-rpath the sidecars we get an
            // infinite rebuild loop. So we first compute whether any change is actually
            // needed, and only touch the binary (which updates its mtime) when it is.
            let existing_rpaths = read_rpaths(binary_path);
            let stale_rpaths: Vec<&String> = existing_rpaths
                .iter()
                .filter(|r| r.contains("/Volumes/"))
                .collect();
            let missing_rpaths: Vec<&&str> = RPATHS
                .iter()
                .filter(|r| !existing_rpaths.iter().any(|e| e == **r))
                .collect();

            // Check whether the binary already has a valid ad-hoc signature.
            // `codesign --verify` exits 0 only for a valid signature.
            let sig_ok = std::process::Command::new("codesign")
                .args(["--verify", "--strict"])
                .arg(binary_path)
                .output()
                .map(|o| o.status.success())
                .unwrap_or(false);

            if stale_rpaths.is_empty() && missing_rpaths.is_empty() && sig_ok {
                // Nothing to do — leave the binary untouched so its mtime is stable.
                continue;
            }

            // Delete stale /Volumes/external/... rpaths left over from the build host.
            for rpath in &stale_rpaths {
                let _ = std::process::Command::new("install_name_tool")
                    .args(["-delete_rpath", rpath])
                    .arg(binary_path)
                    .output();
            }

            // Add any missing rpaths (install_name_tool errors on duplicate LC_RPATH,
            // which is why we checked `missing_rpaths` first).
            for rpath in &missing_rpaths {
                let _ = std::process::Command::new("install_name_tool")
                    .args(["-add_rpath", rpath])
                    .arg(binary_path)
                    .output();
            }

            // install_name_tool invalidated the ad-hoc signature (or it was missing) —
            // re-apply it so Apple Silicon doesn't SIGKILL the binary on launch.
            let _ = std::process::Command::new("codesign")
                .args(["--force", "--sign", "-"])
                .arg(binary_path)
                .output();
        }
    }

    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    println!("cargo:rerun-if-changed={}", manifest_dir.join("src/lib.rs").display());

    let app_commands = parse_invoke_commands(manifest_dir);
    write_app_command_permissions(manifest_dir, &app_commands);
    let command_refs = leaked_command_slice(&app_commands);

    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(command_refs)),
    )
    .expect("error while building tauri application");
}
