// Build script for the folder-import Tauri plugin.
//
// `tauri_plugin::Builder` registers the IPC command names so the Tauri
// codegen can generate the JS<->Rust (and Rust<->native-mobile) glue. It also
// wires the plugin's `android/` and `ios/` directories into the generated
// mobile Gradle/Xcode projects (see gen/android/tauri.settings.gradle, which
// is regenerated by tauri-build from the dependency graph).

const COMMANDS: &[&str] = &[
    "pick_folder_documents",
    "pick_files",
    "install_apk",
    "backup_db_to_downloads",
    "register_share_listener",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .ios_path("ios")
        .try_build()
        .expect("failed to build tauri-plugin for folder-import");
}
