export const INTENDED_PRO_PACKAGING: Record<string, string> = {
  cloud_sync: 'Hosted sync (intended packaging; not sold)',
  cloud_backup: 'Hosted backup (intended packaging; not sold)',
  library_intelligence: 'Hosted library intelligence (intended packaging; not sold)',
  semantic_connections: 'Hosted semantic connections (intended packaging; not sold)',
  knowledge_graph: 'Hosted knowledge graph (intended packaging; not sold)',
  knowledge_gap_detection: 'Hosted knowledge-gap detection (intended packaging; not sold)',
  adaptive_learning_paths: 'Adaptive hosted paths (intended packaging; not sold)',
  ai_tutoring: 'Hosted tutoring (intended packaging; not sold)',
  enhanced_card_generation: 'Hosted card generation (intended packaging; not sold)',
  card_optimizer: 'Hosted card optimizer (intended packaging; not sold)',
  advanced_analytics: 'Advanced hosted analytics (intended packaging; not sold)',
  cloud_document_processing: 'Cloud document processing (intended packaging; not sold)',
  premium_tts: 'Premium hosted TTS (intended packaging; not sold)',
  transcription: 'Hosted transcription (intended packaging; not sold)',
  web_capture: 'Hosted web capture (intended packaging; not sold)',
  integrations: 'Hosted integrations (intended packaging; not sold)',
  automation: 'Hosted automation (intended packaging; not sold)',
  api_access: 'Hosted API access (intended packaging; not sold)',
};
