import {
  LANGUAGE_ANALYTICS_FORMULA_VERSION,
  type AnalyticsEventKind,
  type AnalyticsMetricId,
  type MetricDefinition,
} from "./types";

const event = (...events: AnalyticsEventKind[]) => events;

/**
 * The catalog is the source of truth for IDs, units, denominators, and event
 * provenance. Components should consume these definitions instead of
 * reimplementing a language metric formula.
 */
export const LANGUAGE_ANALYTICS_METRIC_CATALOG: readonly MetricDefinition[] = [
  {
    id: "vocabulary.known_lemmas",
    family: "vocabulary",
    unit: "count",
    sourceEvents: event("lexicon.encounter", "knowledge.state-change"),
    formula: "count distinct lemmas whose latest observed state is known",
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "vocabulary.familiar_lemmas",
    family: "vocabulary",
    unit: "count",
    sourceEvents: event("lexicon.encounter", "knowledge.state-change"),
    formula: "count distinct lemmas whose latest observed state is familiar",
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "vocabulary.learning_lemmas",
    family: "vocabulary",
    unit: "count",
    sourceEvents: event("lexicon.encounter", "knowledge.state-change"),
    formula: "count distinct lemmas whose latest observed state is learning",
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "vocabulary.new_lemmas",
    family: "vocabulary",
    unit: "count",
    sourceEvents: event("lexicon.encounter", "knowledge.state-change"),
    formula: "count distinct lemmas whose latest observed state is new or encountered",
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "exposure.encounters",
    family: "exposure",
    unit: "count",
    sourceEvents: event("lexicon.encounter"),
    formula: "sum encounter events",
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "exposure.unique_lemmas",
    family: "exposure",
    unit: "count",
    sourceEvents: event("lexicon.encounter", "knowledge.state-change"),
    formula: "count distinct lemma IDs observed in the period",
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "exposure.documents",
    family: "exposure",
    unit: "count",
    sourceEvents: event("lexicon.encounter", "reader.session", "listening.session", "coverage.snapshot"),
    formula: "count distinct associated document IDs",
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "lookup.count",
    family: "lookup",
    unit: "count",
    sourceEvents: event("lexicon.lookup"),
    formula: "sum explicit user-initiated lookup events",
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "lookup.per_1000_words",
    family: "lookup",
    unit: "per_1000_words",
    numerator: "lookup.count",
    denominator: "activity.reading_tokens",
    sourceEvents: event("lexicon.lookup", "reader.session"),
    formula: "lookup.count / reading.tokens * 1000; unknown when reading.tokens is zero",
    minimumSampleSize: 1,
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "activity.reading_sessions",
    family: "activity",
    unit: "count",
    sourceEvents: event("reader.session"),
    formula: "count reader.session events, excluding cache-render origins",
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "activity.reading_minutes",
    family: "activity",
    unit: "minutes",
    sourceEvents: event("reader.session"),
    formula: "sum reader durationSeconds / 60",
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "activity.reading_tokens",
    family: "activity",
    unit: "tokens",
    sourceEvents: event("reader.session"),
    formula: "sum reader tokenCount",
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "activity.listening_minutes",
    family: "activity",
    unit: "minutes",
    sourceEvents: event("listening.session"),
    formula: "sum listening durationSeconds / 60",
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "activity.listening_sentences",
    family: "activity",
    unit: "sentences",
    sourceEvents: event("listening.session"),
    formula: "sum listening sentenceCount",
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "activity.speaking_outputs",
    family: "activity",
    unit: "count",
    sourceEvents: event("practice.evidence"),
    formula: "sum speaking and shadowing attempts",
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "activity.writing_outputs",
    family: "activity",
    unit: "count",
    sourceEvents: event("practice.evidence"),
    formula: "sum writing attempts",
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "state.movement_count",
    family: "state",
    unit: "count",
    sourceEvents: event("knowledge.state-change"),
    formula: "sum explicit knowledge state changes; transitions are retained separately",
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "coverage.ratio",
    family: "coverage",
    unit: "ratio",
    numerator: "known lexical tokens",
    denominator: "analyzed lexical tokens",
    sourceEvents: event("coverage.snapshot"),
    formula: "knownTokens / analyzedTokens; pending and stale documents are excluded from the numerator and denominator",
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "coverage.unknown_density",
    family: "coverage",
    unit: "ratio",
    numerator: "unknown lexical tokens",
    denominator: "analyzed lexical tokens",
    sourceEvents: event("coverage.snapshot"),
    formula: "unknownTokens / analyzedTokens; pending and stale documents do not silently count as unknown",
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "difficulty.document_average",
    family: "difficulty",
    unit: "ratio",
    numerator: "ready document difficulty scores",
    denominator: "ready documents",
    sourceEvents: event("coverage.snapshot"),
    formula: "mean difficultyScore over ready documents with a score",
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "evidence.passive_count",
    family: "evidence",
    unit: "count",
    sourceEvents: event("lexicon.encounter", "practice.evidence"),
    formula: "count passive recognition evidence, separate from active production",
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "evidence.active_count",
    family: "evidence",
    unit: "count",
    sourceEvents: event("practice.evidence", "srs.review"),
    formula: "count active production evidence",
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "evidence.passive_confidence",
    family: "evidence",
    unit: "ratio",
    numerator: "passive confidence total",
    denominator: "passive confidence samples",
    sourceEvents: event("lexicon.encounter", "practice.evidence"),
    formula: "mean confidence for passive evidence; null when confidence was not supplied",
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "evidence.active_confidence",
    family: "evidence",
    unit: "ratio",
    numerator: "active confidence total",
    denominator: "active confidence samples",
    sourceEvents: event("practice.evidence", "srs.review"),
    formula: "mean confidence for active evidence; null when confidence was not supplied",
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
  {
    id: "srs.retention",
    family: "srs",
    unit: "ratio",
    numerator: "retained reviews",
    denominator: "reviews",
    sourceEvents: event("srs.review"),
    formula: "retained reviews / reviews; null when there are no review events",
    minimumSampleSize: 1,
    profileScoped: true,
    formulaVersion: LANGUAGE_ANALYTICS_FORMULA_VERSION,
  },
] as const;

const CATALOG_BY_ID = new Map<AnalyticsMetricId, MetricDefinition>(
  LANGUAGE_ANALYTICS_METRIC_CATALOG.map((definition) => [definition.id, definition]),
);

export function getLanguageAnalyticsMetric(id: AnalyticsMetricId): MetricDefinition {
  return CATALOG_BY_ID.get(id)!;
}

export function isLanguageAnalyticsMetricId(value: string): value is AnalyticsMetricId {
  return CATALOG_BY_ID.has(value as AnalyticsMetricId);
}
